name: first workflow

on: 
    push:
        branches:
            - master
    workflow_dispatch:

jobs: 
    first-workflow:
        runs-on: ubuntu-latest

        steps:
            - name: hellow
              run: echo "hello"
            - name: get code files
              uses: actions/checkout@v4.1.1
            - name: list files
              run: ls -l
    Deployment:
        needs: first-workflow
        runs-on: ubuntu-latest
        steps: 
            - name: hellow
              run: |
                echo "hello"
                echo "devops by Github actions"
            
